# Generated by Django 4.0.4 on 2022-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_read_alter_post_blog_viewpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество постов'),
        ),
    ]
