# Generated by Django 3.2.13 on 2022-05-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Post count'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.blog', verbose_name='Blogs owner'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=140, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Title'),
        ),
    ]
